config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin',
    controllers: { sessions: "admin/sessions" },
    skip: [ :registration ]

  root 'pages#index'
  resources :promotions, only: [:show]

  namespace 'admin' do
    root 'dashboards#index'
    resources :categories
    resources :promotions
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :promotions
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :category

  scope :actual, -> { where('start_at < ? AND end_at > ?', Time.now, Time.now) }

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  inherit_resources
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def create
    create!{ collection_url }
  end

  def update
    update!{ collection_url }
  end

private
  def category_params
    params.require(:category).permit(:title)
  end

  def collection
    get_collection_ivar || Category.order(:created_at)
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController
  def index
  end
end

app/controllers/admin/promotions_controller.rb
class Admin::PromotionsController < Admin::BaseController
  def create
    create!{ collection_url }
  end

  def update
    update!{ collection_url }
  end

private
  def promotion_params
    params.require(:promotion).permit(:title, :start_at, :end_at, :cost, :discount_cost, :store, :store_url, :overview, :category_id, :image )
  end

  def collection
    get_collection_ivar || Promotion.order(:created_at)
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  layout 'devise'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@categories = Category.all
    @promotions = Promotion.all
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :init_resource

  def show
    render json: @resource
  end

  private

  def init_resource
    @resource = Promotion.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def active_menu(controller, action=nil)
    if action
      'active' if controller.include?(params[:controller]) && action == params[:action]
    else
      'active' if controller.include?(params[:controller])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admin/_header.haml
%nav.navbar.navbar-default{ role: 'navigation' }
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    = link_to 'MasterCard Lounge', root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav
      %li{ class: active_menu('admin/dashboards', 'index') }
        = link_to 'Dashboard', admin_root_path

    %ul.nav.navbar-nav.navbar-right
      %li.dropdown{ class: active_menu(['admin/promoters', 'admin/captcha', 'admin/settings']) }
        %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
          Администратор
          %b.caret
        %ul.dropdown-menu
          %li.divider
          %li
            = link_to 'Выйти', 'destroy_admin_session_path', method: :delete

app/views/admin/base/_header.haml
%nav.navbar.navbar-default{ role: 'navigation' }
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    = link_to 'MasterCard Lounge', root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav
      %li{ class: active_menu('admin/dashboards', 'index') }
        = link_to 'Dashboard', admin_root_path

      %li{ class: active_menu('admin/categories') }
        = link_to 'Категории', admin_categories_path

      %li{ class: active_menu('admin/promotions') }
        = link_to 'Акции', admin_promotions_path

    %ul.nav.navbar-nav.navbar-right
      %li.dropdown{ class: active_menu(['admin/promoters', 'admin/captcha', 'admin/settings']) }
        %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
          Администратор
          %b.caret
        %ul.dropdown-menu
          %li.divider
          %li
            = link_to 'Выйти', 'destroy_admin_session_path', method: :delete

app/views/admin/base/edit.haml
.page-header
  %h1
    Редактирование
    = link_to 'назад', :back, class: 'btn btn-default pull-right'
%br

= render 'form'

app/views/admin/base/new.haml
.page-header
  %h1
    Создание
    = link_to 'назад', :back, class: 'btn btn-default pull-right'
%br

= render 'form'

app/views/admin/categories/_form.haml
.row
  .col-xs-8.col-xs-offset-2
    = form_for([:admin, resource], html: {role: 'form'}) do |f|
      - if resource.errors.present?
        = render 'admin/partials/errors', errors: resource.errors

      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'

      .form-group
        = f.submit 'Сохранить', class: 'btn btn-success'

app/views/admin/categories/index.haml
.page-header
  %h1
    Категории
    = link_to 'new', new_resource_url, class: 'btn btn-default pull-right'

- if collection.present?
  %table.table
    %thead
      %tr
        %th Название категории
        %th Количество акций
        %th
    %tbody
      - collection.each do |col|
        %tr
          %td= col.title
          %td= col.promotions.actual.count
          %td
            .pull-right.controls
              = link_to 'edit', edit_resource_url(col)
              = link_to 'delete', resource_url(col), method: :delete

app/views/admin/dashboards/index.haml
%h1 Hello

= params[:controller]

app/views/admin/dashboards/offers.haml
%h1
  События на
  = Date.today

.row
  - @cities.each do |city|
    .col-md-8
      %h3
        = link_to city.display_name, city.url
        %small (#{city.name_eng})
      .row
        - city.offers.each do |offer|
          .col-md-8.col-md-offset-1
            = link_to offer.offer_title, offer.url, targer: :blank, class: 'text-success'

%br

app/views/admin/promotions/_form.haml
.row
  .col-xs-8.col-xs-offset-2
    = form_for([:admin, resource], html: {role: 'form'}) do |f|
      - if resource.errors.present?
        = render 'admin/partials/errors', errors: resource.errors

      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'

      .form-group
        = f.label :category_id
        = f.select :category_id, Category.all.map{|i| [i.title, i.id]}, class: 'form-control'

      .form-group
        .row
          .col-xs-8
            = f.label :image
            = f.file_field :image
          .col-xs-4
            - if f.object.image.present?
              = image_tag f.object.image.url, class: 'pull-right img-responsive'

      .form-group
        = f.label :start_at
        = f.date_field :start_at, class: 'form-control'

      .form-group
        = f.label :end_at
        = f.date_field :end_at, class: 'form-control'

      .form-group
        = f.label :cost
        = f.text_field :cost, class: 'form-control'

      .form-group
        = f.label :discount_cost
        = f.text_field :discount_cost, class: 'form-control'

      .form-group
        = f.label :store
        = f.text_area :store, class: 'form-control'

      .form-group
        = f.label :store_url
        = f.text_field :store_url, class: 'form-control'

      .form-group
        = f.submit 'Сохранить', class: 'btn btn-success'

app/views/admin/promotions/index.haml
.page-header
  %h1
    Акции
    = link_to 'new', new_resource_url, class: 'btn btn-default pull-right'

- if collection.present?
  %table.table
    %thead
      %tr
        %th Название акции
        %th Категория
        %th
        %th
    %tbody
      - collection.each do |col|
        %tr
          %td= col.title
          %td= col.category.title
          %td
            = image_tag col.image, width: 150

          %td
            .pull-right.controls
              = link_to 'edit', edit_resource_url(col)
              = link_to 'delete', resource_url(col), method: :delete

app/views/layouts/admin.haml
!!!
%html
  %head
    %title MastercardLounge
    = stylesheet_link_tag    'admin', media: 'all'
    = javascript_include_tag 'admin'
    = csrf_meta_tags

  %body.admin
    = render 'header'
    .container
      - if notice.present?
        .alert.alert-success{ role: 'alert' }= notice

      - if alert.present?
        .alert.alert-danger{ role: 'alert' }= alert

      = yield

app/views/layouts/application.haml
!!!
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/[if IE 9] <html class="ie9 no-js">
/ [if (gt IE 9)|!(IE)]><!
%html.no-js
  / <![endif]
  %head
    / Blockshop Theme Version 2.1.1 by Troop Digital - http://troop.ws/
    %meta{:charset => "UTF-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Skidki
    :javascript
      WebFontConfig = {
        google: { families: ['Lato:400,700', 'lato:400,700', 'lato:400,700', 'lato:400,700', ] }
      };
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    %script{:src => "http://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"}
    %script{:src => "http://cdn.shopify.com/s/files/1/0289/0326/t/2/assets/custom.modernizr.js?5832054538588921208", :type => "text/javascript"}

    :javascript
      var twitterID = '',
      general_external_links_enabled = true,
      general_scroll_to_active_item = false,
      shop_url = 'http://blockshop-theme-deli.myshopify.com',
      shop_money_format = '${{amount}}',
      home_slider_auto_enabled = true,
      home_slider_rotate_frequency = 7000,
      home_widget_twitter_enabled = true,
      home_widget_blog_enabled = true,
      home_widget_instagram_client_id = '76d58d66478e4cd0a54a5dccef206ed6',
      product_zoom_enabled = true,
      product_modal_enabled = true;
  %body.page-deli-blockshop-shopify-theme.template-index.transparent-menu
    = render 'partials/header'

    = yield

    = render 'partials/footer'

app/views/layouts/devise.haml
!!!
%html
  %head
    %title Mastercard Lounge
    = stylesheet_link_tag    'admin', media: 'all'
    = javascript_include_tag 'admin'
    = csrf_meta_tags

    %link{ id: "favicon", href: "/favicon.ico", rel: "icon", type: "image/x-icon"}/
  %body
    = yield

app/views/pages/index.haml
%section.main-content
  %section.slider.dark
    .row
      .slides
        .slide
          %img{:alt => "", :src => "http://cdn.shopify.com/s/files/1/0289/0326/t/2/assets/home-slider-slide-1.jpg?5832054538588921208"}/
          .caption.left.middle.text-left
            .bg
            %h2.title Top 10 Summer Ciders
            %h3.sub-title We share our cider selection, hand-picking the best from around the globe
            %a.button{:href => "#"} Buy Theme
          / .slide_caption
        .slide
          %img{:alt => "", :src => "http://cdn.shopify.com/s/files/1/0289/0326/t/2/assets/home-slider-slide-2.jpg?5832054538588921208"}/
          .caption.center.middle.text-left
            .bg
            %h2.title Divine Dairy
            %h3.sub-title Proudly certified organic biodynamic hand made cheese, now in-store!
            %a.button{:href => "collections/all/products/divine-dairy-double-cream-brie.html"} More Info
          / .slide_caption
        .slide.video
          %img{:alt => "", :src => "http://cdn.shopify.com/s/files/1/0289/0326/t/2/assets/home-slider-slide-3.jpg?5832054538588921208"}/
          %a.play-button{:href => "https://vimeo.com/66766676"}
            .triangle
  .modal.video
    .bg
    %a.close.glyph.cross{"aria-hidden" => "true"}
    .player.columns.large-8
      .flex-video
    .caption.columns.large-4
  .modal-mask
  / #product-slider
  .widgets
    .small-promos
      .row
        .columns.large-4
          .image-text-widget
            %a{:href => "#"}
              %img{:src => "http://cdn.shopify.com/s/files/1/0289/0326/t/2/assets/home-widget-image-text-1.jpg?5832054538588921208"}/
              .caption
                .bg
                .inner
                  %h1 Daily Deli Goods
                  %h2 Shop New
        .columns.large-4
          .image-text-widget
            %a{:href => "#"}
              %img{:src => "http://cdn.shopify.com/s/files/1/0289/0326/t/2/assets/home-widget-image-text-2.jpg?5832054538588921208"}/
              .caption
                .bg
                .inner
                  %h1 From the Bar
                  %h2 Shop Specialty
        .columns.large-4
          .image-text-widget
            %a{:href => "#"}
              %img{:src => "http://cdn.shopify.com/s/files/1/0289/0326/t/2/assets/home-widget-image-text-3.jpg?5832054538588921208"}/
              .caption
                .bg
                .inner
                  %h1 Response &amp; Retina Ready
                  %h2 Buy Theme
  .dark
    .row.header
      .columns.template-blog
        %h2.font-headings.list-of-products.clearfix Список продуктов
        .tags.block.clearfix.colored-links.side-bar
          %h3.title категории
          %ul    
            %li.item
              %span.sort-link.is-checked{ :data => { :filter => '*' } }
                Всё
            - @categories.each do |category|
              %li.item
                %span.sort-link{ :data => { :filter => category.id } }
                  = category.title 

    .row.content
      .product-grid.clearfix
        //это блоки с продуктами
        - 5.times do
          - @promotions.each do |promotion|
            .product-item{ 'data-filter' => promotion.category_id, class: promotion.category_id }
              .image-wrapper
                %span.circle.sale
                  %span
                %a{:href => "#"}
                  = image_tag promotion.image, class: 'lazyOwl'
              .caption
                %p.title
                  = link_to promotion.title, '#'
                %p.vendor
                  = link_to promotion.store, promotion.store_url
                %p.price{ 'data-cost' => promotion.cost, 'data-discount_cost' => promotion.discount_cost }
                  %span.actual-price
                    = promotion.discount_cost
                  %span.old-price
                    = promotion.cost
    .modal-layout
    .modal-product-container
      %section.main-content.modal-product
        %header
        %article.row{:itemscope => "", :itemtype => "http://schema.org/Product", :style => 'padding: 40px 40px 0;'}
          %meta{:content => "", :itemprop => "url"}/
          %meta{:content => "", :itemprop => "image"}/
          .positions.show-for-large-up.active
            .columns.large-6
              %h1.page-title{:itemprop => "name"} Carnaroli Rice
              %h2.vendor{:itemprop => "brand"}
                %a{:href => "#", :title => ""} Евроопт
              .description
                .rte-content{:itemprop => "description"}
                  %p
                    %span Luscious, creamy risotto requires the proper Italian rice. Grown in Piemonte, these "pearls" are pristine, plump and prized-magically maintaining distinct grains, even as they become rich and creamy with the gradual addition of hot broth. Many Northern Italian chefs will only use Carnaroli rice for their risotto. Embellish with chopped parsley and Parmesan cheese, with porcini, truffles or shellfish.
              .prices
                %h3
                  Цена:
                %span.actual-price 120000
                %span.old-price 80000
              .cart-form.custom
                %h3 Вес
                %span 1 кг
            .columns.large-6
              .photos
                .container.clearfix
                  %img{:alt => "Carnaroli Rice", :src => "//cdn.shopify.com/s/files/1/0289/0326/products/rice-01_grande.jpeg?v=1383688847"}/
        %section.row.social-share
          .columns
            %h2.title Поделиться
            %a.glyph.twitter
              %span Tweet
            %a.glyph.facebook
              %span Like
            %a.glyph.googleplus{:href => "https://plus.google.com/share?url=", :onclick => "javascript:window.open(this.href,  '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;", :target => "_blank"}
              %span Plus
        %section.similar-products.row
          %h2.title Похожие продукты
          .product-grid
            .clearfix
            .product-item
              .image-wrapper{:style => "opacity: 1;"}
                %a{:href => "/collections/20-and-over/products/organic-arribbiata-chilli-tomato-sauce"}
                  %img{:alt => "Daylesford Organic Arrabbiata Pasta Sauce", :src => "//cdn.shopify.com/s/files/1/0289/0326/products/condiments-01_large.jpeg?v=1383688889"}/
              / .coll-image-wrap
              .caption
                %p.title
                  %span
                    Томатная паста
                %p.vendor
                  = link_to 'Евроопт', '#'
                %p.price
                  10000

app/views/partials/_footer.haml
%footer.main-footer
  .row.bottom
    .column-1.large-4.columns
      %h2.title Скидки
      .content
        %p.text
          © 2015 С любовью
          %a
    .column-2.large-4.columns{:style => "text-align: right; float: right;"}
      %h2.title Социальные страницы
      #mailing-list-module.content
        .social-follow
          %a.glyph.facebook{"aria-hidden" => "true", :href => "#", :target => "_blank", :title => "Facebook"}
          %a.glyph.twitter{"aria-hidden" => "true", :href => "#", :target => "_blank", :title => "Twitter"}
          %a.glyph.instagram{"aria-hidden" => "true", :href => "#", :target => "_blank", :title => "Instagram"}

app/views/partials/_header.haml
%header.main-header
  .bg
  .row.top
    .columns
      %h1.title.clearfix{:role => "banner"}
        %a{:href => "/", :role => "banner"}
          Volshebno.by
  / .row
  .bottom-row
    .row
      .columns.menu-container
        .main-menu
          %nav.widescreen.clearfix{:role => "navigation"}
            %ul.font-nav
              %li.nav-item
                %a.nav-item-link{:href => "/"}
                  Главная
              %li.nav-item.dropdown
                %a.nav-item-link{:href => "#"}
                  Каталог
                  %span{"aria-hidden" => "true"} ↓
                %ul.sub-nav.catalog
                  %li.sub-nav-item.row
                    .columns.large-3
                      %h3.title Категории
                      %ul
                        %li
                          %a{:href => "#", :title => ""} Все
                        %li
                          %a{:href => "#", :title => ""} Chocolates &amp; Candy
                        %li
                          %a{:href => "#", :title => ""} Oils &amp; Vinegars
                        %li
                          %a{:href => "#", :title => ""} Drinks
                    .columns.large-3
                      %h3.title Price
                      %ul
                        %li
                          %a{:href => "#", :title => ""} Under $10
                        %li
                          %a{:href => "#", :title => ""} $10 - $20
                        %li
                          %a{:href => "collections/20-and-over.html", :title => ""} $20 and over
                    .columns.large-3
                      %h3.title About
                      %ul
                        %li
                          %a{:href => "search.html", :title => ""} Search
                        %li
                          %a{:href => "pages/theme-features.html", :title => ""} Theme Features
                        %li
                          %a{:href => "pages/features.html", :title => ""} Theme Settings
                        %li
                          %a{:href => "pages/contact.html", :title => ""} Contact
      .mobile-tools
        %a.glyph.menu{:href => ""}
        %a.glyph.search{:href => "search.html"}
  .main-menu-dropdown-panel
    .row
  .mobile-menu
    %nav{:role => "navigation"}
      %ul.font-nav
        %li.nav-item
          %a.nav-item-link{:href => "index.html"}
            Home
        %li.nav-item.dropdown
          %a.dropdown-link{:href => "collections/all.html"}
            Catalog
            %span.glyph.plus{"aria-hidden" => "true"}
            %span.glyph.minus{"aria-hidden" => "true"}
          %ul.sub-nav.catalog
            %li.bg
            %li.sub-nav-item
              %a.dropdown-link{:href => ""}
                Collections
                %span.glyph.plus{"aria-hidden" => "true"}
                %span.glyph.minus{"aria-hidden" => "true"}
              %ul.sub-nav
                %li.bg
                %li
                  %a{:href => "collections/all.html", :title => ""} All
                %li
                  %a{:href => "collections/chocolate-candy.html", :title => ""} Chocolates &amp; Candy
                %li
                  %a{:href => "collections/oils-vinegars.html", :title => ""} Oils &amp; Vinegars
                %li
                  %a{:href => "collections/drinks.html", :title => ""} Drinks
            %li.sub-nav-item
              %a.dropdown-link{:href => ""}
                Special
                %span.glyph.plus{"aria-hidden" => "true"}
                %span.glyph.minus{"aria-hidden" => "true"}
              %ul.sub-nav
                %li.bg
                %li
                  %a{:href => "collections/on-sale-1.html", :title => ""} On Sale
                %li
                  %a{:href => "collections/new.html", :title => ""} New
                %li
                  %a{:href => "collections/featured-products.html", :title => ""} Featured Products
        %li.nav-item.dropdown
          %a.dropdown-link{:href => "pages/theme-features.html"}
            Theme
            %span.glyph.plus{"aria-hidden" => "true"}
            %span.glyph.minus{"aria-hidden" => "true"}
          %ul.sub-nav
            %li.bg
            %li.sub-nav-item
              %a{:href => "#", :title => ""} Buy Theme
            %li.sub-nav-item
              %a{:href => "#", :title => ""} Documentation
            %li.sub-nav-item
              %a{:href => "#", :title => ""} Features
            %li.sub-nav-item
              %a{:href => "#", :title => ""} Styles
  .row
    .header-divider